terraform {
  # State is stored in S3 with DynamoDB locking. The bucket and table
  # are created once per AWS account by scripts/bootstrap-tfstate.sh.
  #
  # Run `terraform init -backend-config=backend.hcl` after bootstrap;
  # backend.hcl is generated by the bootstrap script and gitignored.
  backend "s3" {}
}
